import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { Avatar, buzzColors } from "@/components/buzz-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { trpc } from "@/lib/trpc";

export default function MessagesScreen() {
  const { isAuthenticated } = useAuth();
  const conversations = trpc.social.conversations.list.useQuery(undefined, { enabled: isAuthenticated });
  return <ScreenContainer edges={["top", "left", "right"]}><FlatList data={conversations.data ?? []} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => item.user ? <Pressable onPress={() => router.push(`/chat/${item.id}`)} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><Avatar initials={item.user.name.slice(0, 1) || "؟"} tint={buzzColors.indigo} size={54} /><View style={styles.copy}><Text style={styles.name}>{item.user.name}</Text><Text numberOfLines={1} style={styles.last}>{item.lastMessage?.body || "ابدأ محادثة خاصة"}</Text></View><MaterialIcons name="chevron-left" color="#A4A4B4" size={23} /></Pressable> : null} ListHeaderComponent={<View style={styles.header}><Pressable onPress={() => router.push("/add-friend")} style={styles.add}><MaterialIcons name="person-add-alt-1" size={21} color="#FFFFFF" /></Pressable><Text style={styles.heading}>الدردشات</Text></View>} ListEmptyComponent={conversations.isLoading ? <ActivityIndicator color={buzzColors.indigo} style={{ marginTop: 60 }} /> : <View style={styles.empty}><View style={styles.emptyIcon}><MaterialIcons name="chat-bubble-outline" size={34} color={buzzColors.indigo} /></View><Text style={styles.emptyTitle}>لا توجد محادثات بعد</Text><Text style={styles.emptyCopy}>ابدأ من قائمة الأصدقاء، وستظهر هنا المحادثات الحقيقية فقط.</Text><Pressable onPress={() => router.push("/(tabs)/friends")} style={({ pressed }) => [styles.primary, pressed && styles.pressed]}><Text style={styles.primaryText}>فتح الأصدقاء</Text></Pressable></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ list: { paddingHorizontal: 17, paddingBottom: 30 }, header: { height: 62, flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between" }, heading: { color: buzzColors.ink, fontSize: 29, fontWeight: "900", writingDirection: "rtl" }, add: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: buzzColors.indigo }, row: { flexDirection: "row-reverse", alignItems: "center", gap: 12, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#ECECF3", borderRadius: 19, padding: 12, marginBottom: 9 }, copy: { flex: 1, alignItems: "flex-end" }, name: { color: buzzColors.ink, fontSize: 16, fontWeight: "900", writingDirection: "rtl" }, last: { color: buzzColors.muted, fontSize: 12, marginTop: 4, writingDirection: "rtl", textAlign: "right" }, empty: { alignItems: "center", paddingTop: 78, paddingHorizontal: 28 }, emptyIcon: { width: 74, height: 74, borderRadius: 28, backgroundColor: "#EFEEFF", alignItems: "center", justifyContent: "center" }, emptyTitle: { color: buzzColors.ink, fontSize: 21, fontWeight: "900", marginTop: 16, writingDirection: "rtl" }, emptyCopy: { color: buzzColors.muted, fontSize: 13, lineHeight: 22, textAlign: "center", marginTop: 7, writingDirection: "rtl" }, primary: { height: 48, paddingHorizontal: 20, borderRadius: 16, backgroundColor: buzzColors.indigo, marginTop: 18, alignItems: "center", justifyContent: "center" }, primaryText: { color: "#FFFFFF", fontSize: 14, fontWeight: "900", writingDirection: "rtl" }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] } });
